[package]
name = "voxelle-tauri-host"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "voxelle-tauri-host"
path = "src/main.rs"

[dependencies]
rand = "0.8"
serde_json = "1"
rfd = "0.17.2"
tauri = { version = "2.11.3", features = [] }
voxelle-app = { path = "../voxelle-app" }

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dev-dependencies]
tempfile = "3"
