[package]
name = "voxelle-release"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "voxelle-release"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
voxelle-app = { path = "../voxelle-app" }
voxelle-core = { path = "../voxelle-core" }
voxelle-update = { path = "../voxelle-update" }

